# Streamlit Secrets Template
# Copy this file to .streamlit/secrets.toml and add your Firebase credentials
# DO NOT commit the actual secrets file with real values

[firebase]
type = "service_account"
project_id = "YOUR_PROJECT_ID"
private_key_id = "YOUR_PRIVATE_KEY_ID"
private_key = """-----BEGIN PRIVATE KEY-----
YOUR_PRIVATE_KEY_CONTENTS_HERE
-----END PRIVATE KEY-----"""
client_email = "YOUR_CLIENT_EMAIL@YOUR_PROJECT.iam.gserviceaccount.com"
client_id = "YOUR_CLIENT_ID"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "YOUR_CLIENT_X509_CERT_URL"
universe_domain = "googleapis.com"

[firebase_web]
apiKey = "your-api-key"
authDomain = "techiginitectf.firebaseapp.com"
projectId = "techiginitectf"
storageBucket = "techiginitectf.appspot.com"
messagingSenderId = "your-sender-id"
appId = "your-app-id"
databaseURL = ""
