# Streamlit Secrets Template
# Copy this file and add it to your Streamlit deployment secrets
# DO NOT commit the actual secrets file with real values

[firebase]
type = "service_account"
project_id = "techiginitectf"
private_key_id = "your-private-key-id"
private_key = "your-private-key"
client_email = "your-client-email"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "your-cert-url"

[firebase_web]
apiKey = "your-api-key"
authDomain = "techiginitectf.firebaseapp.com"
projectId = "techiginitectf"
storageBucket = "techiginitectf.appspot.com"
messagingSenderId = "your-sender-id"
appId = "your-app-id"
databaseURL = ""
