# Firebase Admin SDK Configuration
[firebase]
type = "service_account"
project_id = "YOUR_PROJECT_ID"  # From service account JSON
private_key_id = "YOUR_PRIVATE_KEY_ID"  # From service account JSON
private_key = '''YOUR_PRIVATE_KEY'''  # From service account JSON, keep the triple quotes
client_email = "YOUR_CLIENT_EMAIL"  # From service account JSON
client_id = "YOUR_CLIENT_ID"  # From service account JSON
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "YOUR_CLIENT_CERT_URL"  # From service account JSON
universe_domain = "googleapis.com"

# Firebase Web Configuration
[firebase_web]
apiKey = "YOUR_WEB_API_KEY"  # From Firebase Console > Project Settings > General
messagingSenderId = "YOUR_MESSAGING_SENDER_ID"  # From Firebase Console > Project Settings > General
appId = "YOUR_APP_ID"  # From Firebase Console > Project Settings > General

# Note: The following values will be automatically generated from your project_id
# authDomain = "YOUR_PROJECT_ID.firebaseapp.com"
# projectId = "YOUR_PROJECT_ID"
# storageBucket = "YOUR_PROJECT_ID.appspot.com"
# databaseURL = "https://YOUR_PROJECT_ID-default-rtdb.firebaseio.com"
